### ISSUE TITLE
`UTBot: Prepare project model` action in command palette

### ISSUE THREAD

**Issue by korifey** [UnitTestBot/UTBotCpp#18]
If project model configuration is failed by one of the reasons: 
- `build` folder is not create
- `compile_commands.json` and `link_commands.json` are failed to generate from CMake/Make
- source folders are not marked as `src` 

then user have no chance to configure project. 

We need explicit command in VSCode command pallete that will repeat aforementioned actions.  Also we should create a special section in Troubleshooting wiki to tell user when that he is able to invoke this command.

**Comment by ladisgin** [comment]
We have `UTBot: configure project` command pallet. But it doesn't reconfigure project if we change `CMakeLists.txt`.
Probably we need add smth like `UTBot: reset and configure project`. That delete build, tmp directories and configure project from zero.
