### ISSUE TITLE
Incomplete type of expected variable for 'void *' argument

### ISSUE THREAD

**Issue by operasfantom** [UnitTestBot/UTBotCpp#186]
## Steps to reproduce

1. Open and configure project `coreutils`
2. Generate tests for `gnulib/lib/free.c`
3. Try to run tests
4. See logs

## Logs
```
/home/utbot/projects/coreutils/utbot_tests/gnulib/lib/free_test.cpp:19:10: error: variable has incomplete type 'void'
    void expected_p = 0;
```

## Test
```cpp
TEST(error, rpl_free_test_1)
{
    __attribute__ ((aligned(16))) unsigned char p = 0;
    rpl_free(&p);
    void expected_p = 0;
    EXPECT_EQ(expected_p, p);
}
```

## Questions
Should we check the pointer if it is freed? Should we check 'void *' output variables at all?

**Comment by Lana243** [comment]
@operasfantom, which version of coreutils have you used?

**Comment by operasfantom** [comment]
> @operasfantom, which version of coreutils have you used?

I used to build on the latest master at that time. But let's switch to v9.1 for testing purposes.
