### ISSUE TITLE
Tests are generated with misaligned addresses for pointers

### ISSUE THREAD

**Issue by operasfantom** [UnitTestBot/UTBotCpp#195]
## Steps to reproduce

1. Open and configure project `coreutils`
2. Choose target `libcoreutils.a`
3. Generate tests for file `gnulib/lib/di-set.c`
4. See tests

## Test
```cpp
TEST(error, di_set_lookup_test_2)
{
    struct di_set dis = {NULL, NULL, (struct di_ent *) 0xff};
    di_set_lookup(&dis, 0UL, 0UL);
    struct di_set expected_dis = {NULL, NULL, NULL};
}
```

## Note
`(struct di_ent *) 0xff` has a misaligned address but requires 8 byte alignment

**Comment by operasfantom** [comment]
Although, KLEE gives an error about that too. Probably the problem lies in KLEE.

```
KLEE: ERROR: gnulib/lib/di-set.c:163: either misaligned address for 0xff or invalid usage of address 0xff with insufficient space
```

**Comment by getN1ght** [comment]
Fixed in this [PR](https://github.com/UnitTestBot/klee/pull/34)

**Comment by operasfantom** [comment]
> Fixed in this [PR](https://github.com/UnitTestBot/klee/pull/34)

Please be kind and add a regression test for this case.
