### ISSUE TITLE
Function that exits normally belongs to regression suite but makes the test fail

### ISSUE THREAD

**Issue by operasfantom** [UnitTestBot/UTBotCpp#197]
Let's say we test a function that exits with status 0. In this case, the test belongs to the regression suite but makes it fail. Do you think it has to be [Death test](https://github.com/google/googletest/blob/main/docs/advanced.md#death-tests)?

![image](https://user-images.githubusercontent.com/31903947/164778058-af992d85-5888-4a68-8e6e-1a0b36fea44d.png)

**Comment by korifey** [comment]
Good suggestion. I think we should use ASSERT_EXIT in such cases.

**Comment by ladisgin** [comment]
Will be done by #252
