### ISSUE TITLE
UTBotCpp does not support test generation for 32bit projects

### ISSUE THREAD

**Issue by llmagic** [UnitTestBot/UTBotCpp#216]
Hi,my working project is an embedded 32bit project, I must add compile flag "-m32" in my Cmakelists.txt
when I use unittestBot C/C++ to config my working project, there would be linking errors below:
```
...
error: /utbot_distr/debs-install/usr/lib/gcc/x86_64-linux-gnu/9/crtbegin.o: incompatible target
warning: skipping incompatible /utbot_distr/debs-install/usr/lib/x86_64-linux-gnu//libdl.so while searching for dl
warning: skipping incompatible /utbot_distr/debs-install/usr/lib/gcc/x86_64-linux-gnu/9//libstdc++.a while searching for stdc++
error: cannot find -lstdc++
...
```
Is that because UTBot not support -m32 compile project? How could I solve this problem?
I installed utbot with __utbot_installer_2021.2.23.sh__ on linux, and it works well with the __[c-example](https://github.com/UnitTestBot/UTBotCpp/tree/main/integration-tests/c-example)__ project.

**Comment by alexey-utkin** [comment]
- 32bit symbolic libraries need to be compiled and added to the project (after fix )
