### ISSUE TITLE
"Couldn't link any file" error when generating tests for project 

### ISSUE THREAD

**Issue by asolqa** [UnitTestBot/UTBotCpp#23]
Version [v1.0.31-alpha ](https://github.com/UnitTestBot/UTBotCpp/releases/tag/v1.0.31-alpha)
[Test project](https://github.com/UnitTestBot/UTBotCpp/tree/v1.0.31-alpha/integration-tests/c-example) 

Steps to reproduce:

1. Select lib folder
2. Right click -> UTbot: Generate Tests for Project

Actual -> FAILED_PRECONDITION: Couldn't link any files
![LinkError](https://user-images.githubusercontent.com/13063781/145059298-21042109-7450-4a89-8a68-614379d23b7b.png)
![LinkError0](https://user-images.githubusercontent.com/13063781/145058989-b85156fa-9031-408c-a98d-24d7fe57d3e1.png)
Expected -> Test should be generated

**Comment by sava-cska** [comment]
@asolqa check again

**Comment by korifey** [comment]
@sava-cska please write about issue status

**Comment by sava-cska** [comment]
1) I can't reproduce this problem in this form, but I had files ..._test.cpp with message "KLEE has internal error and doesn't generate any test". I think, it is the same problem.
2) This problem is fixed, you can try again

**Comment by asolqa** [comment]
Checked on [1.0.57](https://github.com/UnitTestBot/UTBotCpp/actions/runs/1610709401): no error link error message
Looks fixed.
