### ISSUE TITLE
Optimize makefiles generated for project

### ISSUE THREAD

**Issue by Lana243** [UnitTestBot/UTBotCpp#234]
## Steps to reproduce:
1. Configure `coreutils`.
2. Run `UTBotCpp` via CLI: ```./utbot generate --project-path <path to coreutils> project```.
3. After generation finished go to `build/utbot/make` directory in `coreutils`.
4. See disk usage (for unix systems run `du -sh`)

## Enhancement
Currently, makefiles use ~0.5Gb of disk. However, there is a lot of copy-paste there. Disk usage can be strongly improved by moving common part of code for files from one target into another file and reusing it afterwards.

**Comment by ladisgin** [comment]
will be done in duplicate #248
