### ISSUE TITLE
Simplification UTBot usages under the Windows in pair with WSL 2

### ISSUE THREAD

**Issue by ladisgin** [UnitTestBot/UTBotCpp#250]
Describe the scenario for user with Windows-based project toolchain.
- Installation scenarios:
  - **UTBotCpp** server into WSL2 
  - **UTBotCpp** VC code plugin on Windows

Need to resole the problem with the running of generated tests (seems to be related to mixing  _gcc_ ang _UTBot clang_ toolchains)

**Comment by alexey-utkin** [comment]
The document 
  https://github.com/UnitTestBot/UTBotCpp/wiki/docker-free-wsl2
was created, that describes simplified approach for UTBot usage on Windows.
