### ISSUE TITLE
Strict Aliasing Rule Option

### ISSUE THREAD

**Issue by S1eGa** [UnitTestBot/UTBotCpp#256]
In order to optimize `resolve` method in Klee we can restrict number of possibly created forks by adding option like `-strict-aliasing` to klee. Helpful option for C++, as Strict Aliasing violation leads to UB.

Also it is a good option to limit number of states, which can be generated after `resolve`. E.g. if problem is not in casting pointers, we will force klee to skip some useless states by adding this option.

**Comment by ladisgin** [comment]
Can't be resolved without Clang type info
