### ISSUE TITLE
Klee ignores concretization effects in `callExternalFunction`

### ISSUE THREAD

**Issue by getN1ght** [UnitTestBot/UTBotCpp#260]
Consider the following code:

```c
#include <stdlib.h>
#include <assert.h>
#include "klee/klee.h"

int main() {
    int x = klee_int("x");
    int y = abs(x);
    if (x >= 0) {
        klee_assert(y == x);
    }
}
```

Compiled and launched with
```
clang -emit-llvm -c -g -O0 -Xclang -disable-O0-optnone abs.c
klee --external-calls=all abs.bc
```

When `abs` external call is made klee concretize the value of `x`. It is expected behavior, but then assert fails with: `KLEE: ERROR: exmple.cpp:10: ASSERTION FAIL: y == x`, because klee did not track effects of argument concretization.

During arguments concretization in function call we can add corresponding constraint in order to take this particular value into account in the future.

**Comment by ladisgin** [comment]
fixed by https://github.com/UnitTestBot/klee/commit/b2e8b2a3484dfc2ef72878f03e9b7f655081c680
