### ISSUE TITLE
Incorrect capture of the empty macros from CMakeLists.txt setup

### ISSUE THREAD

**Issue by alexey-utkin** [UnitTestBot/UTBotCpp#276]
From discussion:
https://github.com/UnitTestBot/UTBotJava/discussions/170

minimal reproducer:
`main.cpp`
```
#include <iostream>

int EXPORTS f(int a, int b) {
    return a + b;
}
int main () {
    std::cout << "awa!" << std::endl;
    return 1;
} 
```

`CMakeLists.txt`
```
cmake_minimum_required(VERSION 3.20)
project(example1)

set(CMAKE_CXX_STANDARD 11)

add_executable(example1 main.cpp)
target_compile_definitions(example1 PUBLIC EXPORTS=)
```

**Comment by ladisgin** [comment]
Problem with empty exports in `target_compile_definitions(example1 PUBLIC EXPORTS=)`
It's work well with bear, but then we use `set(CMAKE_EXPORT_COMPILE_COMMANDS ON)`
it generate command like `"command": "/utbot_distr/install/bin/clang++ -DEXPORTS=\"\"  -std=gnu++11 -o CMakeFiles/example1.dir/main.cpp.o -c /home/utbot/emamble/main.cpp"`

**Comment by ladisgin** [comment]
We use ShellExec with there all arg is string that escape some symbols like " and \
