### ISSUE TITLE
Add a comment section containing error message to error tests 

### ISSUE THREAD

**Issue by operasfantom** [UnitTestBot/UTBotCpp#280]
KLEE prints `.err` files containing error message, file location, line number, and more. For example:

```
Error: memory error: invalid pointer: free
File: /tmp/code/code.c
Line: 8
assembly.ll line: 23
Stack: 
	#000000023 in main (=1, =36263824) at /tmp/code/code.c:8
Info: 
	address: 36291136
	next: object at 36963008 of size 23
		MO19[23] allocated at main():  %3 = alloca i32, align 4
	prev: object at 36291112 of size 8
		MO33[8] allocated at main():  %6 = alloca i8*, align 8
```

This information may be used in order to produce comments above the error test or its function call, similar to UTBotJava's approach.

**Comment by alexey-utkin** [comment]
While the fix, please, take a look at SARIF report creation procedure. Seems the most of code can be extended a bit and be reused.

**Comment by operasfantom** [comment]
Well done!
