### ISSUE TITLE
Publish C/C++ CLI docker images on GitHub Packages

### ISSUE THREAD

**Issue by victoriafomina** [UnitTestBot/UTBotCpp#295]
**Description**

_UTBot Cloud_ runs tests for C/C++ code in docker containers with _C/C++ CLI_. For CI/CD processes we need to know whether docker container corresponding to the latest C/C++ CLI version is compatible with UTBot Cloud or not. Thus, we need to publish its images somewhere and use it in CD processes.

**Expected behavior**

C/C++ CLI image is published on GitHub Packages on every push to _main_ branch.

**Environment**

GitHub Actions, GitHub Packages

**Potential alternatives**

No alternatives.

**Context**

Not applicable.

**Comment by ladisgin** [comment]
closed by #296
