### ISSUE TITLE
Do not init pointers as struct fields members to NULL

### ISSUE THREAD

**Issue by tang4530** [UnitTestBot/UTBotCpp#314]
UTBot always init pointers as struct fields members to NULL or invaild values.
This operation will generate many error cases，which is not what we expected. 
I hope you can optimize this scenario.

![image](https://user-images.githubusercontent.com/107664060/177242641-dbfc1367-8eb6-4468-9d60-2f03627d0431.png)

**Comment by ladisgin** [comment]
@getN1ght, same problem #325

**Comment by ladisgin** [comment]
Fixed https://github.com/UnitTestBot/klee/commit/8137e92b28d144221d5cc33bdd2142b771eac43f
