### ISSUE TITLE
Not support anonymous union in struct

### ISSUE THREAD

**Issue by tang4530** [UnitTestBot/UTBotCpp#317]
![image](https://user-images.githubusercontent.com/107664060/177940430-95d910b0-5463-4b89-9d9a-16afac5f9e33.png)

**Comment by ladisgin** [comment]
Hello @tang4530, thanks for request.

**Description**
UTBotCpp don't generate test for struct with anonymous union.
```cpp
typedef struct {
  int a;
  union {
    int b;
    int c;
  } u;
} Info;

int inner(Info l) {
  if (l.a == 1) {
    l.u.b = 4;
    return 0;
  }
  if (l.a == 2) {
    l.u.c = 5;
    return 1;
  }
  return -1;
}
```

**Expected behavior**
Test will generated same as struct with named union.

**Comment by tang4530** [comment]
I have modified anonymous union to the named union. But some compile errors occured.
![image](https://user-images.githubusercontent.com/107664060/178179217-e552d49b-7724-4ef0-a7fe-ed2208e10b53.png)
