### ISSUE TITLE
Run tests fail

### ISSUE THREAD

**Issue by ladisgin** [UnitTestBot/UTBotCpp#32]
makefile for tests use default gcc and link utbot x86_64-linux-gnu

**Comment by korifey** [comment]
Tested on WSL2, Ubuntu 20.04, attaching repro solution:
[test_utbot.zip](https://github.com/UnitTestBot/UTBotCpp/files/7727028/test_utbot.zip)

**Comment by ladisgin** [comment]
In tests makefile
`/home/utbot/release/utbot_distr/debs-install/usr/bin/ld -r $(LDFLAGS) -fuse-ld=gold -B /home/utbot/release/utbot_distr/debs-install/usr/lib/gcc/x86_64-linux-gnu/9 -B /home/utbot/release/utbot_distr/debs-install/usr/lib/x86_64-linux-gnu -B /home/utbot/release/utbot_distr/debs-install/usr/lib64/ -B /usr/lib64 -B /home/utbot/release/utbot_distr/debs-install/usr/lib64/ -B /usr/lib64 -o /home/utbot/logs/utbot/tmp/tmp/utbot-GFXJ/test_utbot/recompiled/test_utbot /home/utbot/logs/utbot/tmp/tmp/utbot-GFXJ/test_utbot/recompiled/CMakeFiles/test_utbot.dir/main.cpp.o /home/utbot/logs/utbot/tmp/tmp/utbot-GFXJ/test_utbot/recompiled/CMakeFiles/test_utbot.dir/MyTest.cpp.o -L/home/utbot/release/utbot_distr/debs-install/usr/lib64/ -L/home/utbot/release/utbot_distr/debs-install/usr/lib64/ && objcopy --redefine-sym main=old_main /home/utbot/logs/utbot/tmp/tmp/utbot-GFXJ/test_utbot/recompiled/test_utbot`
no -B flag in ld
