### ISSUE TITLE
For Linked List：Improvement 

### ISSUE THREAD

**Issue by tang4530** [UnitTestBot/UTBotCpp#325]
For linked lists, most cases generated are error. But the source code is actually fine. Have you considered how to optimize this?

![image](https://user-images.githubusercontent.com/107664060/179131443-8c5164f8-f6ac-41d3-837a-3a5ff3c4200f.png)

**Comment by ladisgin** [comment]
Fixed https://github.com/UnitTestBot/klee/commit/8137e92b28d144221d5cc33bdd2142b771eac43f
