### ISSUE TITLE
"Debug+Asserts" runtime build is used for KLEE [BUG]

### ISSUE THREAD

**Issue by operasfantom** [UnitTestBot/UTBotCpp#338]
**Description**
KLEE supports different build types for its runtimes (`klee-uclibc`,  `posix`, `libcxx`, `fp`, etc) as configured by `KLEE_RUNTIME_BUILD_TYPE` cmake option. Currently, the default value `"Debug+Asserts"` is used. However, the optimised version `""Release+Debug+Asserts""` can be used. That one is also tested in `"No TCMalloc, optimised runtime"` CI configuration. 

Note, this switch can be implemented, if and only if there are **no** cases of undefined behaviour in runtimes, including custom `fp` runtime. I am emphasizing this, because otherwise, the compiler may produce unexpected results.

**To Reproduce**
1. Open `klee/build.sh` script
2. There is no `KLEE_RUNTIME_BUILD_TYPE` option there
3. Run `./build.sh` in `klee` directory
4. Check out logs and see `-- KLEE_RUNTIME_BUILD_TYPE: Debug+Asserts`

**Expected behavior**
Optimised runtime is used.

**Actual behavior**
Default debug runtime is used

**Visual proofs (screenshots, logs)**
Not applicable.

**Environment**
Any.

**Additional context**
Top [CMakeLists.txt](https://github.com/klee/klee/blob/master/CMakeLists.txt#L463) in KLEE source code.

**Comment by ladisgin** [comment]
For some implementation of the I/O function, such as "fgets", `"Release"` build significantly increases the generation time

**Comment by operasfantom** [comment]
> For some implementation of the I/O function, such as "fgets", `"Release"` build significantly increases the generation time

Any ideas why it has the opposite effect? Is it possible to optimise implementation of such functions for Release build?
