### ISSUE TITLE
CLion plugin: add opportunity to disable plugin for projects that don't need utbot

### ISSUE THREAD

**Issue by vol0n** [UnitTestBot/UTBotCpp#399]
**Description**
By default IJ plugins are enabled/disabled for all projects. But user may want to disable utbot for some projects. 

**Expected behavior**
Add a UI component to disable plugin for project. If plugin is disabled it should not send any notifications, not expose any actions to user, and preferably UI components like toolwindows, project panes

**Comment by ladisgin** [comment]
#### Solution
