### ISSUE TITLE
[BUG] Suggestions on WSL2 installation documentation improvement

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#400]
- [x] add link to [WSL2 installation instructions](https://github.com/UnitTestBot/UTBotCpp/wiki/docker-free-wsl2) from [installing server](https://github.com/UnitTestBot/UTBotCpp/wiki/install-server) page.

**All comments below are about https://github.com/UnitTestBot/UTBotCpp/wiki/docker-free-wsl2 page**
- [x]  delete command line prompt from command text, so user would be able to copy/past them without additional action, e.g. `utbot@userhwlp:~$ mkdir utbotcpp` could be just `mkdir utbotcpp`
- [x]  `wget` command has `--no-check-certificate` flag which is generally not commended, I think we need to either delete or explain why it is needed
- [x] _**To run correctly UTBot server needs..**_ section explains what additionally should be installed on the sever after user started UTBotCpp server. Probably it is better to move this section to beginning.
- [x] add a note that `utbot_server_restart.sh` should be used to start server too (there is no dedicated script for that)

**Comment by ladisgin** [comment]
Done https://github.com/UnitTestBot/UTBotCpp/wiki/docker-free-wsl2
