### ISSUE TITLE
[BUG] Suggestions on Docker documentation improvements

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#403]
**Description**
Suggestions are about Docker installation page - https://github.com/UnitTestBot/UTBotCpp/wiki/testing-release-utbotcpp-in-docker

- Add link to this instruction to https://github.com/UnitTestBot/UTBotCpp/wiki/install-server page
- Add it to Table of content, Installation part
- There is no information about `g++` installation, do we assume it should be there?
- It suggests to install `apt update && apt install sudo vim openssh-server unzip gcc-9 g++-9 make -y` - why `Vim` is installed?

**Comment by ladisgin** [comment]
@tyuldashev 
> Add link to this instruction to https://github.com/UnitTestBot/UTBotCpp/wiki/install-server page
> Add it to Table of content, Installation part

This guide is intended for developers to be able to quickly upgrade the system to check the release.

> There is no information about g++ installation, do we assume it should be there?

Yes, we need GCC or Clang for work UTBot.

> It suggests to install apt update && apt install sudo vim openssh-server unzip gcc-9 g++-9 make -y - why Vim is installed?

Just console text editor that can help in some next testing.

**Comment by tyuldashev** [comment]
Okay let's leave it as is.
