### ISSUE TITLE
[BUG] Unnecessary "utbot_abs_error" constant added to the test

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#405]
**Version**
2022.8.233
**Description**
UTBot adds unused constant to the test 
`static const float utbot_abs_error = 1e-6;`

Generate code for following function
```c
char a_or_b(char a, char b) {
  if (a == 'a')
    return a;
  else 
    return b;
}
```

Result is
```c
#include "snippet_dot_c_test.h"

#include "gtest/gtest.h"
namespace UTBot {
static const float utbot_abs_error = 1e-6;


#pragma region regression
TEST(regression, a_or_b_test_1)
{
    char actual = a_or_b('h', 'c');
    EXPECT_EQ('c', actual);
}

TEST(regression, a_or_b_test_2)
{
    char actual = a_or_b('a', 'c');
    EXPECT_EQ('a', actual);
}

#pragma endregion
}
```

generated constant `utbot_abs_error` is unused and seems unecessary.

**Comment by ladisgin** [comment]
@alexey-utkin, we can add check that function has float in parameters or move this value to header

**Comment by alexey-utkin** [comment]
We need to use
EXPECT_FLOAT_EQ and EXPECT_DOUBLE_EQ instead of EXPECT_NEAR.
It makes utbot_abs_error variable obsolete and resolves the problem with NAN and INFINITY comparison.
