### ISSUE TITLE
[BUG] Tests run on outdated code

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#408]
Version: 2022.8.233

**Description**
If user generates tests, runs them and updates code then next running still uses 'old' code.

**To Reproduce**
1. Write a function like that
```
short min_short(short a, short b) {
    if (a < b) {
        return a;
    }
    return b;
}
```
2. Generate tests for the file
3. Run tests with coverage - both passed
4. Update condition from `a < b` to `a > b` and save the file
5. Run generated tests again - both test passed again. **Expected that one test fails.**

I've checked that code is actually updated on the remote server.
It doesn't happen if user skips step 3 and run only modified code.

**Comment by ladisgin** [comment]
Make don't recompile binary because it depends on the wrapper not source file.
#### Solution
Add source file to dependency of test binary.

**Comment by tyuldashev** [comment]
Also it could lead to more obvious problem: for instance user renames some function inside file from `my_main2` to `my_main3` and then regenerates tests and try to run them. `Run Tests` fails with error (see pic below). Mentioned log contains following information.

![image](https://user-images.githubusercontent.com/10035839/187866740-85eab1f8-1bd2-4c0e-b9ad-1fba09b4018d.png)

```
/home/utbot/utbot_distr/2022.8.242/utbot_distr/debs-install/usr/bin/ld.gold: warning: Cannot export local symbol '__asan_extra_spill_area'
/home/utbot/remote/SampleDocker2/tests/../tests/helloworld_dot_c_test.h:326: error: undefined reference to 'my_main3_helloworld_c'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
/home/utbot/remote/SampleDocker2/tests/../tests/__helloworld_shared.mk:28: recipe for target '/home/utbot/remote/SampleDocker2/tests/../build/utbot_build/recompiled/helloworld' failed
make[1]: *** [/home/utbot/remote/SampleDocker2/tests/../build/utbot_build/recompiled/helloworld] Error 1
/home/utbot/utbot_distr/2022.8.242/utbot_distr/debs-install/usr/bin/ld.gold: warning: Cannot export local symbol '__asan_extra_spill_area'
/home/utbot/remote/SampleDocker2/tests/../tests/helloworld_dot_c_test.h:326: error: undefined reference to 'my_main3_helloworld_c'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
/home/utbot/remote/SampleDocker2/tests/../tests/__helloworld_obj.mk:28: recipe for target '/home/utbot/remote/SampleDocker2/tests/../build/utbot_build/recompiled/helloworld' failed
make[1]: *** [/home/utbot/remote/SampleDocker2/tests/../build/utbot_build/recompiled/helloworld] Error 1
/home/utbot/remote/SampleDocker2/tests/helloworld.mk:46: recipe for target 'run' failed
make: *** [run] Error 2
```

**Comment by tyuldashev** [comment]
Dedicated issue for my comment - #543
