### ISSUE TITLE
[BUG] Too little test generated for simple comparison function

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#422]
**To Reproduce**
1. Run test generation for following simple comparison function:
```c
int my_cmp(int a, int b) {
    return (a == b);
}
```
2. UTbot generates only one test:
```c
TEST(regression, my_cmp_test_1)
{
    int actual = my_cmp(0, 0);
    EXPECT_EQ(1, actual);
}
```

**Expected that at least two tests would be generated, one when values are equal (the existing one) and another where parameter values are different.**

**Comment by ladisgin** [comment]
UTBot cover whole source code
