### ISSUE TITLE
UTBot don't decorate struct field [BUG]

### ISSUE THREAD

**Issue by ladisgin** [UnitTestBot/UTBotCpp#465]
**Description**
UTBot don't decorate struct field

**To Reproduce**
1. Generate tests for `equals` from  `c-example/lib/keywords/keywords_dot_c_test.cpp`
2. Try run tests

**Expected behavior**
Test passed

**Actual behavior**
Compilation error

**Visual proofs (screenshots, logs)**
```cpp
TEST(regression, equals_test_1)
{
    _Bool actual = equals({
        .public = 0L,
        .private = 0L
    });
    EXPECT_EQ(true, actual);
}
```

**Comment by ladisgin** [comment]
#470

**Comment by tyuldashev** [comment]
This specific problem fixed but there are other similar problems like #534 and #535
