### ISSUE TITLE
[BUG] Odd verification for empty string in generated test

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#479]
**Description**
UTBot creates empty string as input parameter and then checks its not changed during function call by comparing it with not empty char array.

**To Reproduce**
Generate tests for following code:
```c 
int my_strlen(char *s)
{
    char *p;
    int k;
    p = s;
    k = 0;
    while (*p != '\0')
    {
        p++;
        k++;
    }
    return k;
}
```

**Expected behavior**
For regression passing tests are generated

**Actual behavior**
One of the tests looks like this:
```c

TEST(regression, my_strlen_test_1)
{
    char s[] = "";
    int actual = my_strlen(s);
    EXPECT_EQ(0, actual);
    char expected_s[] = {'\0', 'c', 'a', 'c', 'c', 'c', 'c', 'c', 'c', '\0'};
    for (int it_3_0 = 0; it_3_0 < 10; it_3_0 ++) {
        EXPECT_EQ(expected_s[it_3_0], s[it_3_0]);
    }
}
```

Note  that it initially creates empty string `char s[] = ""` but then expects `char expected_s[] = {'\0', 'c', 'a', 'c', 'c', 'c', 'c', 'c', 'c', '\0'};` which obviously fails.

**Comment by ladisgin** [comment]
duplicate #463
