### ISSUE TITLE
[BUG] Cannot generate tests with custom build script which uses Makefile

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#491]
**Description**
For some reason UTBot cannot generate test for pretty simple project, which uses `make` tool.

**To Reproduce**
1. Open attached project - [Smoke1.zip](https://github.com/UnitTestBot/UTBotCpp/files/9766845/Smoke1.zip)
2. Configure UTBot - everything looks OK
3. Try to generate test for any file in `src` folder

**Expected behavior**
Tests are supposed to be generated.

**Actual behavior**
UTBot fails with error:

```
compile_commands.json doesn't contain a command for source file /home/utbot/remote/temp/Sample1/src/main.c
```

`compile_commands.json` has following content:
```
[
    {
        "arguments": [
            "gcc",
            "-c",
            "-o",
            "../build/main",
            "func.c"
        ],
        "directory": "/home/utbot/remote/temp/Sample1/src",
        "file": "func.c"
    },
    {
        "arguments": [
            "gcc",
            "-c",
            "-o",
            "../build/main",
            "main.c"
        ],
        "directory": "/home/utbot/remote/temp/Sample1/src",
        "file": "main.c"
    }
]
```

If I change value of `file` parameter from `func.c` to `src\func.c` then it starts working.

**Comment by ladisgin** [comment]
duplicate #316
