### ISSUE TITLE
Possible UI/UX improvements of UTBot Wizard

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#494]
**Description**
Below are list of possible improvement which could be implemented to make UTBot installation wizard easier to use.

**Suggestions**
* Add ability to configure SFTP plugin (when it's installed) along with UTBot settings, at least settings which are required for minimal setup, like *port* and *login*.
* Reduce descriptions on `Server setup` page and probably group them in one place, so all setting fields could be grouped together. The text tells a lot about SFTP plugin, so when previous task would be accomplished then less explanation would be required.
* Reduce descriptions on `Project Setup` page. There are number of duplications there, for example each of two settings name repeated twice. Description of CMake options seems trivial and could be either removed or expanded in case it has some special meaning.
* Finishing page probably could be removed, so there are only 3 wizard pages. Anyway it report success even when there are problems in previous steps, for example when UTBot server cannot be reached.
* Do we really need that 'Install' ability on first page, anybody uses it? Could it be good time to remove it and reduce maintenance cost for the future?

**Comment by alexey-utkin** [comment]
@ladisgin @tyuldashev 
You can try new wirad in pre-release
https://github.com/UnitTestBot/UTBotCpp/releases/tag/2022.10.6
