### ISSUE TITLE
[BUG] No tests generated for function calling function from another module

### ISSUE THREAD

**Issue by vol0n** [UnitTestBot/UTBotCpp#517]
**Description**
Generation for function that calls function from another target produces no tests saying that it leads to klee internal error

**To Reproduce**
1. Open the c-example project
2. Choose `libsrc.a` target and set `use stubs` to true
3. Generate tests for function `other_module_call` at least two times. One of attempts will fail

**Expected behavior**
Tests are supposed to be generated and linked with stubs

**Actual behavior**
No tests are generated. 

**Visual proofs (screenshots, logs)**
Generated test file:
```
/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#include "calc_dot_c_test.h"

#include "gtest/gtest.h"
namespace UTBot {
// Some tests for function 'other_module_call' were skipped, as execution of function leads KLEE to the internal error. See console log for more details.

// Tests for other_module_call were not generated. Maybe the function is too complex.



}
```
Logs: [logs.txt](https://github.com/UnitTestBot/UTBotCpp/files/9873336/logs.txt)

**Environment**
latest main or latest release 2022.10.4

**Comment by tyuldashev** [comment]
Tests are generated but there could be identical ones - #547
