### ISSUE TITLE
minnum [BUG]

### ISSUE THREAD

**Issue by S1eGa** [UnitTestBot/UTBotCpp#526]
Consider the following test case:
```c++
#include "klee/klee.h"
#include <math.h>
#include <assert.h>

int main() {
    double a = 0.0, b = NAN;

    if (fmin(a, b) == a) {
        return 1;
    } else {
        assert(0);
        return 2;
    }
}
```

According to the `fmin` specification we should return 1, but instead assertion fails in another branch during klee execution (you can check this by running via KLEE and compiled elf). 
Would be great if @sava-cska will see.

**Comment by ladisgin** [comment]
Moved to KLEE issue https://github.com/UnitTestBot/klee/issues/61
