### ISSUE TITLE
Fields on 'Server Setup' page of wizard are misaligned

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#530]
**To Reproduce**
1. Start 'Run UTBot: Quickstart` wizard
2. Proceed to `Server setup` page

**Actual behavior**
Fields and labels are misaligned

![image](https://user-images.githubusercontent.com/10035839/200812375-a7073314-98b1-490f-a13e-3d0d6e862592.png)

**Expected behavior**
* `Host`, `GRPC port` and `SFTP port` are start at the same horizontal position. Now it seems that port settings are more to the right than `Host`
* Input fields for `Host`, `GRPC port` and `SFTP port` are start at the same horizontal position no matter of the length of label
* Messages `Successfully pinged...` are the same vertical position as ports labels, now they are more the top than labels

**Comment by tyuldashev** [comment]
To be honest I don't see many changes in **_v2022.10.8_**, all the mentioned problems are still there
![image](https://user-images.githubusercontent.com/10035839/201881035-2461aecd-de9c-4aa4-bf78-dbf128bc14c1.png)

**Comment by alexey-utkin** [comment]
@tyuldashev 
"GRPC Port" and "SFTP Port" are now right aligned.

**Comment by tyuldashev** [comment]
@alexey-utkin I see, though my suggestion was to left align all three labels and all three fields, not just two fields.
