### ISSUE TITLE
Error to find compile_commands.json on projects with Makefile. 

### ISSUE THREAD

**Issue by kichunya** [UnitTestBot/UTBotCpp#569]
**Description**
When trying to use utbot on [libbpf ](https://github.com/libbpf/libbpf) project run falls with next error:

![image](https://user-images.githubusercontent.com/32273736/208407260-333c7af7-51e2-4bfc-a580-59c055312181.png)

**To Reproduce**
1) Follow [issue 490](https://github.com/UnitTestBot/UTBotCpp/issues/490) to configure the project.
2) Try to generate tests for any C file.

**Additional information**
Due to absence of cmake in this project, compile_commands.json is as follows:

![image](https://user-images.githubusercontent.com/32273736/208409047-5e2b233c-089d-42e1-b0ef-c17c71771934.png)

Now utbot cannot parse it.

**Comment by ladisgin** [comment]
#575
