### ISSUE TITLE
Check Object_File_Exe_Test

### ISSUE THREAD

**Issue by sava-cska** [UnitTestBot/UTBotCpp#570]
**Description**
Test `Object_File_Exe_Test` in `Server_Test.cpp` was changed: `expectedStatusCountMap{{testsgen::TEST_PASSED, 8}}` transformed to `expectedStatusCountMap{{testsgen::TEST_PASSED, 7}}`. However, in the previous version KLEE generated 7 regression tests and 4 errors, but UTBot received 8 PASSED, so, probably, error test was PASSED. It is necessary to verify it.

**To Reproduce**
Launch test `Object_File_Exe_Test` in `Server_Test.cpp`.

**Additional context**
Check why we have 7 tests and is it right or wrong.

**Comment by kichunya** [comment]
Previously count of passed tests was changed to 8 due to let the tests pass. But now it fails because of only 7 tests passed. 
[sava-cska](https://github.com/sava-cska) changed it back to 7.
