### ISSUE TITLE
Add interactive mode to klee

### ISSUE THREAD

**Issue by sava-cska** [UnitTestBot/UTBotCpp#6]
When we generate tests for all functions in a file (or in a project), we run klee as many times as there are functions in the file (or in the project). The file, which we send to klee, doesn't change between launches add we lose time on preprocessing, which launches every time.
Solution: send to klee array of entry_points and run preprocessing one time, after that run ordinary process to generate tests

**Comment by korifey** [comment]
Why not use 'fork' instead of 'list of entry_points'?
